version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sr_fretes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker:/etc/mysql/conf.d
      - microservice-persistent:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    restart: always
