version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
      container_name: mup_delivery_api
    ports:
      - "8000:80"
    environment:
        MYSQL_DATABASE: sr_fretes
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: secret
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sr_fretes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker:/etc/mysql/conf.d
      - microservice-persistent:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    restart: always
